# Generated by Django 3.2.16 on 2022-11-20 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0003_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'permissions': (('can_publish', 'Может опубликовать'), ('can_be_published', 'Должно быть одобрено модератором')), 'verbose_name': 'новость', 'verbose_name_plural': 'новости'},
        ),
    ]
