# Generated by Django 3.2.16 on 2022-11-20 18:47

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('app_news', '0004_alter_news_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'permissions': (('can_publish', 'Может опубликовать'),), 'verbose_name': 'новость', 'verbose_name_plural': 'новости'},
        ),
        migrations.AddField(
            model_name='news',
            name='tag',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
