# Generated by Django 3.2.16 on 2022-11-24 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0008_alter_blogpost_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='active',
            new_name='is_active',
        ),
    ]
