# Generated by Django 3.2.16 on 2022-11-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0012_blogpost_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
