# Generated by Django 3.2.16 on 2022-11-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentary',
            name='user',
        ),
        migrations.AlterField(
            model_name='commentary',
            name='user_name',
            field=models.CharField(default='Anonymous', max_length=20),
            preserve_default=False,
        ),
    ]
