# Generated by Django 3.2.16 on 2022-11-24 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0009_rename_active_blogpost_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='post',
            new_name='description',
        ),
    ]
