# Generated by Django 3.2.16 on 2022-11-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0013_alter_blogpost_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.ImageField(upload_to='files/')),
            ],
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='file',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='file',
            field=models.ManyToManyField(blank=True, to='app_news.BlogImage'),
        ),
    ]
