# Generated by Django 3.2.16 on 2022-11-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0014_auto_20221128_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimage',
            name='files',
            field=models.FileField(upload_to=''),
        ),
    ]
