# Generated by Django 3.2.16 on 2022-11-28 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0017_alter_blogimage_files'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogimage',
            old_name='files',
            new_name='file',
        ),
    ]
